version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/django-rest-api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "⬆️ deps"
      include: "scope"
