[tool.black]
line-length = 88
target-version = ['py311']
skip-string-normalization = false
extend-exclude = '''
/(
    migrations
  | venv
  | __pycache__
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88
skip = ["venv", "migrations", "__pycache__"]

[tool.flake8]
max-line-length = 88
extend-ignore = [
    "E203",  # compatible avec black (espaces autour des tranches)
    "W503"   # ignore "line break before binary operator"
]
exclude = [
    ".git",
    "__pycache__",
    "migrations",
    "venv",
    "config/asgi.py",
    "config/wsgi.py"
]
max-complexity = 10
select = ["E", "F", "W", "C90"]
