# Generated by Django 5.2.7 on 2025-10-30 09:13

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'uuid',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ('description', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'permission',
                    models.CharField(
                        choices=[
                            ('AUTHOR', 'Author'),
                            ('CONTRIBUTOR', 'Contributor'),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    'role',
                    models.CharField(
                        choices=[
                            (
                                'Auteur et Contributeur du projet',
                                'Auteur et Contributeur du projet',
                            ),
                            ('Contributeur', 'Contributeur'),
                        ],
                        max_length=255,
                    ),
                ),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contributeur',
                'verbose_name_plural': 'Contributeurs',
                'ordering': ['project', 'user'],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                (
                    'tag',
                    models.CharField(
                        choices=[
                            ('BUG', 'Bug'),
                            ('FEATURE', 'Feature'),
                            ('TASK', 'Task'),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    'priority',
                    models.CharField(
                        choices=[
                            ('LOW', 'Low'),
                            ('MEDIUM', 'Medium'),
                            ('HIGH', 'High'),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('TODO', 'To Do'),
                            ('IN_PROGRESS', 'In Progress'),
                            ('FINISHED', 'Finished'),
                        ],
                        default='TODO',
                        max_length=20,
                    ),
                ),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Issue',
                'verbose_name_plural': 'Issues',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('BACK_END', 'Back-end'),
                            ('FRONT_END', 'Front-end'),
                            ('iOS', 'iOS'),
                            ('ANDROID', 'Android'),
                        ],
                        max_length=20,
                    ),
                ),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-created_time'],
            },
        ),
    ]
