# Generated by Django 5.2.7 on 2025-10-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_issue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[
                    ("TODO", "To Do"),
                    ("IN_PROGRESS", "In Progress"),
                    ("FINISHED", "Finished"),
                ],
                default="TODO",
                max_length=20,
            ),
        ),
    ]
