# Generated by Django 5.2.7 on 2025-10-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributor",
            name="permission",
            field=models.CharField(
                choices=[("AUTHOR", "Author"), ("CONTRIBUTOR", "Contributor")],
                max_length=20,
            ),
        ),
    ]
