# Generated by Django 5.2.7 on 2025-10-21 09:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_contributor_user_alter_project_author_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={
                'ordering': ['-created_time'],
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
            },
        ),
        migrations.AlterModelOptions(
            name='contributor',
            options={
                'ordering': ['project', 'user'],
                'verbose_name': 'Contributeur',
                'verbose_name_plural': 'Contributeurs',
            },
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={
                'ordering': ['-created_time'],
                'verbose_name': 'Issue',
                'verbose_name_plural': 'Issues',
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={
                'ordering': ['-created_time'],
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
            },
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('description', 'issue', 'author_user')},
        ),
        migrations.AlterUniqueTogether(
            name='issue',
            unique_together={('title', 'project', 'assignee_user')},
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('title', 'author_user')},
        ),
    ]
