# Generated by Django 5.2.7 on 2025-10-22 11:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'projects',
            '0007_alter_comment_options_alter_contributor_options_and_more',
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='created_time',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
