# Generated by Django 5.2.7 on 2025-10-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_contributor_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='role',
            field=models.CharField(
                choices=[
                    (
                        'Auteur et Contributeur du projet',
                        'Auteur et Contributeur du projet',
                    ),
                    ('Contributeur', 'Contributeur'),
                ],
                max_length=255,
            ),
        ),
    ]
